import { useState, useCallback, createContext, useContext, useEffect } from 'react';

export type Language = 'en' | 'fr' | 'ar';

const translations = {
  en: {
    title: 'Qibla Finder',
    subtitle: 'Find the direction of the Kaaba',
    detecting: 'Detecting your location…',
    locationAccess: 'Location Access',
    locationDesc: 'Please enable GPS to calculate the Qibla direction from your location.',
    enableLocation: 'Enable Location',
    enableCompass: 'Enable Compass',
    compassDesc: 'Allow compass access for live directional guidance.',
    activateCompass: 'Activate Compass',
    calculating: 'Calculating direction…',
    compassNA: 'Compass not available — showing Qibla bearing',
    facingQibla: 'You are facing Qibla',
    turnPhone: 'Turn your phone to align with the arrow',
    qiblaBearing: 'Qibla bearing',
    coordinates: 'Coordinates',
    qibla: 'Qibla',
    distanceToMecca: 'Distance to Mecca',
    bismillah: 'بِسْمِ اللَّهِ الرَّحْمَنِ الرَّحِيمِ',
    N: 'N', E: 'E', S: 'S', W: 'W',
    qiblaVerse: 'قَدْ نَرَىٰ تَقَلُّبَ وَجْهِكَ فِي السَّمَاءِ ۖ فَلَنُوَلِّيَنَّكَ قِبْلَةً تَرْضَاهَا ۚ فَوَلِّ وَجْهَكَ شَطْرَ الْمَسْجِدِ الْحَرَامِ ۚ وَحَيْثُ مَا كُنتُمْ فَوَلُّوا وُجُوهَكُمْ شَطْرَهُ — القرآن الكريم 2:144',
    // compass section
    noSensorsTitle: 'No motion sensors detected',
    noSensorsBody: 'Use the controls below to manually rotate the compass',
    currentHeading: 'Your Current Heading',
    reset: '⊙ Reset',
    dragAdjust: 'Drag to adjust heading (fine control)',
    alignedMessage: '✅ Aligned with Qibla!',
    // gravity north finder
    gravityTitle: 'Gravity-Based North Finder',
    gravityDesc: "No stars or moon? Use your phone's gravity sensors to detect north without a compass.",
    motionUnsupported: 'Motion sensors not supported on your device.',
    gravityHowItWorks: 'How It Works',
    gravityStep1: 'Hold phone level in front of you (screen facing forward)',
    gravityStep2: 'Slowly rotate 360° while keeping it level',
    gravityStep3: 'Watch the acceleration readings below',
    gravityStep4: "When gravity reads mostly Z-axis, you're closest to True North",
    gravityStart: '▶ Start Measuring',
    gravityStop: '⏹ Stop Measuring',
    xAxisLabel: 'X-Axis (Left/Right):',
    yAxisLabel: 'Y-Axis (Forward/Back):',
    zAxisLabel: 'Z-Axis (Up/Down):',
    statusLabel: 'Status:',
    proTips: '💡 Pro Tips:',
    tip1: 'Remove any magnetic materials nearby',
    tip2: 'Keep phone perfectly level while rotating',
    tip3: 'Rotate slowly for better readings',
    tip4: 'Z-axis should be highest (gravity pulling down)',
    tip5: 'When X & Y are near zero, you\'re aligned',
    // navigation guides
    navigationTitle: 'Direction Guides',
    navigationDesc: 'No compass working? Use these guides to find your Qibla direction.',
    starsTab: 'Stars',
    moonTab: 'Moon',
    sunTab: 'Sun',
    compassTab: 'Compass',
    // sun method
    sunMethodTitle: 'Sun Position Method',
    sunMethodDesc: 'During daytime, the sun is your best natural compass.',
    sunStep1: 'The sun rises in the East and sets in the West.',
    sunStep2: 'At solar noon (when the sun is highest), it points due South in the Northern Hemisphere and due North in the Southern Hemisphere.',
    sunStep3: 'Place a stick vertically in the ground. The shadow points roughly North (in Northern Hemisphere) or South (in Southern Hemisphere).',
    sunStep4: 'Mark the shadow tip, wait 15 minutes, mark again. A line between the marks runs East-West.',
    sunShadowTip: 'The shadow stick method works best within 2 hours of solar noon for the most accurate results.',
    // last resort
    lastResortTitle: 'If You Cannot Determine the Qibla',
    lastResortDesc: 'If after trying all methods you still cannot determine the Qibla direction, know that Allah is Merciful and your prayer is still valid.',
    lastResortHadith1: 'The Prophet ﷺ said: "What is between the East and the West is Qibla."',
    lastResortHadith1Source: '— Sunan al-Tirmidhī 344, graded Hasan',
    lastResortHadith2: 'Allah says: "And to Allah belongs the East and the West. So wherever you turn, there is the Face of Allah."',
    lastResortHadith2Source: '— Quran 2:115',
    lastResortAdvice: 'Do your best to estimate the direction, make your intention sincere, and pray. Allah does not burden a soul beyond its capacity.',
    // night navigation (kept)
    nightNavigationTitle: 'Night Navigation',
    nightNavigationDesc: 'No compass working? Use these celestial guides to find your Qibla direction.',
    findPolaris: 'Find Polaris (North Star)',
    bigDipperStep: 'Find the Big Dipper (7 bright stars forming a ladle shape)',
    pointerStarsStep: 'Follow the pointer stars at the edge of the "cup" upward',
    polarisDistanceStep: "Polaris is about 5x their distance away — it's moderately bright",
    polarisNorthInfo: 'This points TRUE NORTH',
    outstretchedArmTip: 'Use your outstretched arm as a reference. From shoulder to fingertip ≈ 20° arc.',
    southernCrossTitle: 'Find the Southern Cross (Crux)',
    southernCrossInstructions: 'Locate the Southern Cross (4 bright stars in a cross pattern)',
    southernCrossAxis: 'Follow the long axis downward for about 4.5x the cross length',
    southernCrossPole: 'This points toward the South Celestial Pole',
    southernCrossNorth: 'Therefore: North is directly opposite',
    moonMethodTitle: 'Moon Position Method',
    moonNorthernInfo: 'In Northern Hemisphere: Moon rises in the EAST and sets in the WEST',
    moonSouthernInfo: 'In Southern Hemisphere: Moon rises in the EAST and sets in the WEST (but appears more northward in the sky)',
    moonToday: "Today's Moon:",
    lunarDayText: 'Lunar Day:',
    moonRiseText: 'Approximate rise: ~',
    moonNote: 'Moon method is less accurate than stars. Use stars if available.',
    compassInstructionsHeader: 'Phone Compass Method',
    compassInstructions: 'Even without GPS, your phone\'s compass can work:',
    compassStep1: 'Close any magnetized objects (headphones, metal)',
    compassStep2: 'Make sure phone isn\'t in airplane mode',
    compassStep3: 'Restart the compass app',
    compassStep4: 'Slowly rotate phone 360° (figure-eight motion)',
    compassStep5: 'This "calibrates" the magnetometer',
    yourQiblaDirection: 'Your Qibla Direction:',
    quickReference: 'Quick Direction Reference',
    north: 'North', east: 'East', south: 'South', west: 'West',
    note1:'Your location affects compass accuracy. Magnetic north varies by location on Earth.',
    Magnetic_Variance: 'Magnetic variance (declination) is the angle difference between magnetic north and true north at your location. It can affect compass accuracy.',
    Direction: 'Direction',
    Sensors_active_and_reading: 'Sensors active and reading data',
    Updates_daily: 'Updates daily',
    Times_calculated: 'Times calculated for your location and timezone',
    Magnetic_Accuracy: 'Magnetic Accuracy',
      Poor: 'Poor',
      Fair: 'Fair',
      Good: 'Good',
    Prayer_Times: 'Prayer Times',
    welcome: 'Welcome',
    tapToFind: 'Tap the button below to find the Qibla direction from your current location.',
    findQibla: 'Find Qibla Direction',
    tryAgain: 'Try Again',
    iosLocationSettings: 'Safari may not support location on this device. For the best experience, please open this app in Google Chrome instead.',
  },
  fr: {
    title: 'Localisateur de Qibla',
    subtitle: 'Trouvez la direction de la Kaaba',
    detecting: 'Détection de votre position…',
    locationAccess: 'Accès à la localisation',
    locationDesc: 'Veuillez activer le GPS pour calculer la direction de la Qibla depuis votre position.',
    enableLocation: 'Activer la localisation',
    enableCompass: 'Activer la boussole',
    compassDesc: 'Autorisez l’accès à la boussole pour un guidage directionnel en temps réel.',
    activateCompass: 'Activer la boussole',
    calculating: 'Calcul de la direction…',
    compassNA: 'Boussole non disponible — affichage du relèvement Qibla',
    facingQibla: 'Vous êtes face à la Qibla',
    turnPhone: 'Tournez votre téléphone pour aligner la flèche',
    qiblaBearing: 'Relèvement Qibla',
    coordinates: 'Coordonnées',
    qibla: 'Qibla',
    distanceToMecca: 'Distance à La Mecque',
    bismillah: 'بِسْمِ اللَّهِ الرَّحْمَنِ الرَّحِيمِ',
    N: 'N', E: 'E', S: 'S', W: 'O',
    qiblaVerse: 'قَدْ نَرَىٰ تَقَلُّبَ وَجْهِكَ فِي السَّمَاءِ ۖ فَلَنُوَلِّيَنَّكَ قِبْلَةً تَرْضَاهَا ۚ فَوَلِّ وَجْهَكَ شَطْرَ الْمَسْجِدِ الْحَرَامِ ۚ وَحَيْثُ مَا كُنتُمْ فَوَلُّوا وُجُوهَكُمْ شَطْرَهُ — القرآن الكريم 2:144',
    noSensorsTitle: 'Aucun capteur de mouvement détecté',
    noSensorsBody: 'Utilisez les commandes ci-dessous pour faire pivoter la boussole manuellement',
    currentHeading: 'Votre cap actuel',
    reset: '⊙ Réinitialiser',
    dragAdjust: 'Glissez pour ajuster le cap (contrôle fin)',
    alignedMessage: '✅ Aligné avec la Qibla !',
    gravityTitle: 'Localisateur de nord basé sur la gravité',
    gravityDesc: 'Pas d’étoiles ni de lune ? Utilisez les capteurs de gravité de votre téléphone pour détecter le nord sans boussole.',
    motionUnsupported: 'Capteurs de mouvement non pris en charge sur votre appareil.',
    gravityHowItWorks: 'Comment ça marche',
    gravityStep1: 'Tenez le téléphone à plat devant vous (écran vers l’avant)',
    gravityStep2: 'Tournez lentement sur 360° en le gardant bien horizontal',
    gravityStep3: 'Observez les valeurs d’accélération ci-dessous',
    gravityStep4: 'Quand la gravité est principalement sur l’axe Z, vous êtes proche du nord vrai',
    gravityStart: '▶ Démarrer la mesure',
    gravityStop: '⏹ Arrêter la mesure',
    xAxisLabel: 'Axe X (Gauche/Droite) :',
    yAxisLabel: 'Axe Y (Avant/Arrière) :',
    zAxisLabel: 'Axe Z (Haut/Bas) :',
    statusLabel: 'État :',
    proTips: '💡 Astuces pro :',
    tip1: 'Éloignez tout matériau magnétique à proximité',
    tip2: 'Gardez le téléphone parfaitement horizontal pendant la rotation',
    tip3: 'Tournez lentement pour de meilleures mesures',
    tip4: 'L’axe Z doit être le plus élevé (gravité vers le bas)',
    tip5: 'Quand X et Y sont proches de zéro, vous êtes aligné',
    navigationTitle: 'Guides de direction',
    navigationDesc: 'Boussole défaillante ? Utilisez ces guides pour trouver la direction de la Qibla.',
    starsTab: 'Étoiles',
    moonTab: 'Lune',
    sunTab: 'Soleil',
    compassTab: 'Boussole',
    sunMethodTitle: 'Méthode du Soleil',
    sunMethodDesc: 'En journée, le soleil est votre meilleure boussole naturelle.',
    sunStep1: 'Le soleil se lève à l\'Est et se couche à l\'Ouest.',
    sunStep2: 'À midi solaire (quand le soleil est au plus haut), il indique le Sud dans l\'hémisphère nord et le Nord dans l\'hémisphère sud.',
    sunStep3: 'Plantez un bâton verticalement dans le sol. L\'ombre pointe approximativement vers le Nord (hémisphère nord) ou le Sud (hémisphère sud).',
    sunStep4: 'Marquez le bout de l\'ombre, attendez 15 minutes, marquez à nouveau. La ligne entre les deux marques est Est-Ouest.',
    sunShadowTip: 'La méthode du bâton fonctionne mieux dans les 2 heures autour du midi solaire.',
    lastResortTitle: 'Si vous ne pouvez pas déterminer la Qibla',
    lastResortDesc: 'Si après avoir essayé toutes les méthodes vous ne pouvez toujours pas déterminer la direction de la Qibla, sachez qu\'Allah est Miséricordieux et que votre prière reste valide.',
    lastResortHadith1: 'Le Prophète ﷺ a dit : « Ce qui est entre l\'Est et l\'Ouest est la Qibla. »',
    lastResortHadith1Source: '— Sunan al-Tirmidhī 344, classé Hasan',
    lastResortHadith2: 'Allah dit : « À Allah appartiennent l\'Est et l\'Ouest. Où que vous vous tourniez, là est la Face d\'Allah. »',
    lastResortHadith2Source: '— Coran 2:115',
    lastResortAdvice: 'Faites de votre mieux pour estimer la direction, soyez sincère dans votre intention, et priez. Allah n\'impose à aucune âme une charge supérieure à sa capacité.',
    nightNavigationTitle: 'Navigation nocturne',
    nightNavigationDesc: 'Boussole défaillante ? Utilisez ces repères célestes pour trouver la direction de la Qibla.',
    findPolaris: 'Trouver Polaris (Étoile Polaire)',
    bigDipperStep: 'Repérez la Grande Ourse (7 étoiles brillantes formant une casserole)',
    pointerStarsStep: 'Suivez les deux étoiles pointeuses au bord de la « casserole » vers le haut',
    polarisDistanceStep: 'Polaris se trouve environ 5 fois cette distance — elle est modérément brillante',
    polarisNorthInfo: 'Cela indique le NORD VRAI',
    outstretchedArmTip: 'Utilisez votre bras tendu comme référence. De l’épaule au bout des doigts ≈ 20° d’arc.',
    southernCrossTitle: 'Trouver la Croix du Sud (Crux)',
    southernCrossInstructions: 'Localisez la Croix du Sud (4 étoiles brillantes en forme de croix)',
    southernCrossAxis: 'Suivez le grand axe vers le bas sur environ 4,5 fois la longueur de la croix',
    southernCrossPole: 'Cela pointe vers le pôle céleste sud',
    southernCrossNorth: 'Donc : le nord est exactement à l’opposé',
    moonMethodTitle: 'Méthode de la position de la Lune',
    moonNorthernInfo: 'Dans l’hémisphère nord : la Lune se lève à l’EST et se couche à l’OUEST',
    moonSouthernInfo: 'Dans l’hémisphère sud : la Lune se lève à l’EST et se couche à l’OUEST (mais apparaît plus au nord dans le ciel)',
    moonToday: 'Lune du jour :',
    lunarDayText: 'Jour lunaire :',
    moonRiseText: 'Lever approximatif : ~',
    moonNote: 'La méthode lunaire est moins précise que les étoiles. Préférez les étoiles si possible.',
    compassInstructionsHeader: 'Méthode de la boussole du téléphone',
    compassInstructions: 'Même sans GPS, la boussole de votre téléphone peut fonctionner :',
    compassStep1: 'Éloignez tout objet magnétisé (écouteurs, métal)',
    compassStep2: 'Assurez-vous que le téléphone n’est pas en mode avion',
    compassStep3: 'Redémarrez l’application boussole',
    compassStep4: 'Tournez lentement le téléphone à 360° (mouvement en forme de 8)',
    compassStep5: 'Cela « calibre » le magnétomètre',
    yourQiblaDirection: 'Votre direction Qibla :',
    quickReference: 'Référence rapide des directions',
    north: 'Nord', east: 'Est', south: 'Sud', west: 'Ouest',
    note1: 'Votre position affecte la précision de la boussole. Le nord magnétique varie selon l’endroit sur Terre.',
    Magnetic_Variance: 'Magnetic variance (declination) is the angle difference between magnetic north and true north at your location. It can affect compass accuracy.',
    Direction: 'Direction',
    Sensors_active_and_reading: 'Capteurs actifs et lisant des données',
    Updates_daily: 'Mis à jour quotidiennement',
    Times_calculated: 'Heures calculées pour votre emplacement et votre fuseau horaire',
    Magnetic_Accuracy: 'Précision magnétique',
    Poor: 'Faible',
    Fair: 'Moyenne',
    Good: 'Bonne',
    Prayer_Times: 'Heures de prière',
    welcome: 'Bienvenue',
    tapToFind: 'Appuyez sur le bouton ci-dessous pour trouver la direction de la Qibla depuis votre position.',
    findQibla: 'Trouver la Qibla',
    tryAgain: 'Réessayer',
    iosLocationSettings: 'Safari peut ne pas prendre en charge la localisation sur cet appareil. Pour une meilleure expérience, veuillez ouvrir cette application dans Google Chrome.',
  },
  ar: {
    title: 'باحث القبلة',
    subtitle: 'اعثر على اتجاه الكعبة المشرفة',
    detecting: 'جارٍ تحديد موقعك…',
    locationAccess: 'الوصول إلى الموقع',
    locationDesc: 'يرجى تفعيل GPS لحساب اتجاه القبلة من موقعك.',
    enableLocation: 'تفعيل الموقع',
    enableCompass: 'تفعيل البوصلة',
    compassDesc: 'اسمح بالوصول إلى البوصلة للإرشاد الاتجاهي المباشر.',
    activateCompass: 'تفعيل البوصلة',
    calculating: 'جارٍ حساب الاتجاه…',
    compassNA: 'البوصلة غير متاحة — عرض زاوية القبلة',
    facingQibla: 'أنت تواجه القبلة',
    turnPhone: 'أدر هاتفك لمحاذاة السهم',
    qiblaBearing: 'زاوية القبلة',
    coordinates: 'الإحداثيات',
    qibla: 'القبلة',
    distanceToMecca: 'المسافة إلى مكة',
    bismillah: 'بِسْمِ اللَّهِ الرَّحْمَنِ الرَّحِيمِ',
    N: 'ش', E: 'شر', S: 'ج', W: 'غ',
    qiblaVerse: 'قَدْ نَرَىٰ تَقَلُّبَ وَجْهِكَ فِي السَّمَاءِ ۖ فَلَنُوَلِّيَنَّكَ قِبْلَةً تَرْضَاهَا ۚ فَوَلِّ وَجْهَكَ شَطْرَ الْمَسْجِدِ الْحَرَامِ ۚ وَحَيْثُ مَا كُنتُمْ فَوَلُّوا وُجُوهَكُمْ شَطْرَهُ — القرآن الكريم 2:144',
    noSensorsTitle: 'لم يتم الكشف عن مستشعرات الحركة',
    noSensorsBody: 'استخدم التحكمات أدناه لتدوير البوصلة يدويًا',
    currentHeading: 'اتجاهك الحالي',
    reset: '⊙ إعادة تعيين',
    dragAdjust: 'اسحب لضبط الاتجاه (تحكم دقيق)',
    alignedMessage: '✅ محاذاة مع القبلة!',
    gravityTitle: 'باحث الشمال بالجاذبية',
    gravityDesc: 'لا توجد نجوم أو قمر؟ استخدم مستشعرات الجاذبية في هاتفك لاكتشاف الشمال بدون بوصلة.',
    motionUnsupported: 'مستشعرات الحركة غير مدعومة على جهازك.',
    gravityHowItWorks: 'كيف يعمل',
    gravityStep1: 'أمسك الهاتف بشكل مستوٍ أمامك (الشاشة للأمام)',
    gravityStep2: 'أدر ببطء 360 درجة مع الحفاظ على الاستواء',
    gravityStep3: 'راقب قراءات التسارع أدناه',
    gravityStep4: 'عندما تكون الجاذبية غالبًا على المحور Z، أنت قريب من الشمال الحقيقي',
    gravityStart: '▶ بدء القياس',
    gravityStop: '⏹ إيقاف القياس',
    xAxisLabel: 'المحور X (يسار/يمين):',
    yAxisLabel: 'المحور Y (أمام/خلف):',
    zAxisLabel: 'المحور Z (أعلى/أسفل):',
    statusLabel: 'الحالة:',
    proTips: '💡 نصائح احترافية:',
    tip1: 'أزل أي مواد مغناطيسية قريبة',
    tip2: 'حافظ على الهاتف مستويًا تمامًا أثناء الدوران',
    tip3: 'أدر ببطء لقراءات أفضل',
    tip4: 'يجب أن يكون المحور Z هو الأعلى (الجاذبية تسحب للأسفل)',
    tip5: 'عندما يكون X و Y قريبين من الصفر، أنت محاذٍ',
    navigationTitle: 'أدلة الاتجاه',
    navigationDesc: 'البوصلة لا تعمل؟ استخدم هذه الأدلة لإيجاد اتجاه القبلة.',
    starsTab: 'النجوم',
    moonTab: 'القمر',
    sunTab: 'الشمس',
    compassTab: 'البوصلة',
    sunMethodTitle: 'طريقة الشمس',
    sunMethodDesc: 'خلال النهار، الشمس هي أفضل بوصلة طبيعية لديك.',
    sunStep1: 'الشمس تشرق من الشرق وتغرب في الغرب.',
    sunStep2: 'عند الظهيرة الشمسية (عندما تكون الشمس في أعلى نقطة)، تشير إلى الجنوب في نصف الكرة الشمالي وإلى الشمال في نصف الكرة الجنوبي.',
    sunStep3: 'ضع عصا عموديًا في الأرض. الظل يشير تقريبًا نحو الشمال (في نصف الكرة الشمالي) أو الجنوب (في نصف الكرة الجنوبي).',
    sunStep4: 'ضع علامة عند طرف الظل، انتظر 15 دقيقة، ضع علامة أخرى. الخط بين العلامتين يمثل اتجاه الشرق-الغرب.',
    sunShadowTip: 'طريقة العصا تعمل بشكل أفضل خلال ساعتين من الظهيرة الشمسية.',
    lastResortTitle: 'إذا لم تستطع تحديد القبلة',
    lastResortDesc: 'إذا جربت جميع الطرق ولم تستطع تحديد اتجاه القبلة، اعلم أن الله رحيم وأن صلاتك صحيحة.',
    lastResortHadith1: 'قال النبي ﷺ: «ما بين المشرق والمغرب قبلة.»',
    lastResortHadith1Source: '— سنن الترمذي 344، حسن',
    lastResortHadith2: 'قال الله تعالى: ﴿وَلِلَّهِ الْمَشْرِقُ وَالْمَغْرِبُ ۚ فَأَيْنَمَا تُوَلُّوا فَثَمَّ وَجْهُ اللَّهِ﴾',
    lastResortHadith2Source: '— القرآن الكريم 2:115',
    lastResortAdvice: 'اجتهد في تقدير الاتجاه، وأخلص نيتك، وصلِّ. لا يكلف الله نفسًا إلا وسعها.',
    nightNavigationTitle: 'الملاحة الليلية',
    nightNavigationDesc: 'البوصلة لا تعمل؟ استخدم هذه الدلائل السماوية لإيجاد اتجاه القبلة.',
    findPolaris: 'ابحث عن النجم القطبي (بولاريس)',
    bigDipperStep: 'ابحث عن الدب الأكبر (7 نجوم ساطعة تشكل شكل المغرفة)',
    pointerStarsStep: 'اتبع النجمين المؤشرين في حافة «الكوب» للأعلى',
    polarisDistanceStep: 'النجم القطبي يبعد حوالي 5 أضعاف تلك المسافة — وهو ساطع بدرجة معتدلة',
    polarisNorthInfo: 'هذا يشير إلى الشمال الحقيقي',
    outstretchedArmTip: 'استخدم ذراعك الممدود كمرجع. من الكتف إلى طرف الأصابع ≈ 20 درجة قوسية.',
    southernCrossTitle: 'ابحث عن الصليب الجنوبي (Crux)',
    southernCrossInstructions: 'حدد موقع الصليب الجنوبي (4 نجوم ساطعة بشكل صليب)',
    southernCrossAxis: 'اتبع المحور الطويل للأسفل لحوالي 4.5 أضعاف طول الصليب',
    southernCrossPole: 'هذا يشير نحو القطب السماوي الجنوبي',
    southernCrossNorth: 'لذلك: الشمال في الاتجاه المعاكس تمامًا',
    moonMethodTitle: 'طريقة موقع القمر',
    moonNorthernInfo: 'في النصف الشمالي: يطلع القمر من الشرق ويغرب في الغرب',
    moonSouthernInfo: 'في النصف الجنوبي: يطلع القمر من الشرق ويغرب في الغرب (لكنه يظهر أكثر شمالًا في السماء)',
    moonToday: 'قمر اليوم:',
    lunarDayText: 'اليوم القمري:',
    moonRiseText: 'الطلوع التقريبي: ~',
    moonNote: 'طريقة القمر أقل دقة من النجوم. استخدم النجوم إن أمكن.',
    compassInstructionsHeader: 'طريقة بوصلة الهاتف',
    compassInstructions: 'حتى بدون GPS، يمكن أن تعمل بوصلة هاتفك:',
    compassStep1: 'أبعد أي أجسام مغناطيسية (سماعات، معدن)',
    compassStep2: 'تأكد أن الهاتف ليس في وضع الطيران',
    compassStep3: 'أعد تشغيل تطبيق البوصلة',
    compassStep4: 'أدر الهاتف ببطء 360 درجة (حركة على شكل رقم 8)',
    compassStep5: 'هذا «يعاير» المغناطيسي',
    yourQiblaDirection: 'اتجاه القبلة لديك:',
    quickReference: 'مرجع سريع للاتجاهات',
    north: 'شمال', east: 'شرق', south: 'جنوب', west: 'غرب',
    note1: 'موقعك يؤثر على دقة البوصلة. الشمال المغناطيسي يختلف حسب المكان على الأرض.',
    Magnetic_Variance: 'تباين مغناطيسي',
    Direction: 'اتجاه',
    Sensors_active_and_reading: 'المستشعرات نشطة وتقرأ',
    Updates_daily: 'تحديثات يومية',
    Times_calculated: 'الأوقات محسوبة لموقعك والمنطقة الزمنية الخاصة بك',
    Magnetic_Accuracy: 'دقة المغناطيسية',
     Poor: 'ضعيفة',
     Fair: 'متوسطة',
     Good: 'جيدة',
    Prayer_Times: 'أوقات الصلاة',
    welcome: 'مرحباً',
    tapToFind: 'اضغط على الزر أدناه لتحديد اتجاه القبلة من موقعك الحالي.',
    findQibla: 'تحديد اتجاه القبلة',
    tryAgain: 'حاول مرة أخرى',
    iosLocationSettings: 'قد لا يدعم Safari الموقع على هذا الجهاز. للحصول على أفضل تجربة، يرجى فتح هذا التطبيق في Google Chrome.',
  },
} as const;

export type Translations = {
  [K in keyof typeof translations['ar']]: string;
};

export function useLanguage() {
  const [language, setLanguage] = useState<Language>('ar'); // Default to 'ar' initially
  const [isHydrated, setIsHydrated] = useState(false);

  useEffect(() => {
    // This runs only on the client after hydration
    const storedLang = localStorage.getItem('language') as Language | null;
    const defaultLang: Language = storedLang || 'ar';
    setLanguage(defaultLang);
    setIsHydrated(true);
  }, []);

  const t = translations[language];
  const isRTL = language === 'ar';

  const changeLanguage = useCallback((lang: Language) => {
    setLanguage(lang);
    localStorage.setItem('language', lang);
  }, []);

  return { language, t, isRTL, changeLanguage, isHydrated };
}

export { translations };